### ISSUE TITLE
Would you even consider Kafka as an option for the eventstore?

### ISSUE THREAD

**Issue by willmccullough** [thenativeweb/wolkenkit-eventstore#11] opened 2018-09-20 05:05 UTC
For my team's current project, we are speculating using CQRS and event sourcing. After a bit of searching, we stumbled across your projects and they're very interesting. Wolkenkit is starting to look like a viable option for part of our infrastructure. However, there are a few things I'm concerned about. We're pretty determined to use Kafka for the event store and I noticed that this library only supports SQL databases. Do you ever see this library being compatible with Kafka? Also, have you ever considered Kakfa as an event store? If so, why did you choose SQL databases instead?

**Comment by goloroden** [comment] 2018-09-20 05:26
Hi @willmccullough 😊 

Thanks for your interest in wolkenkit, and thanks for bringing up this question. Actually, we have been asked this a few times before.

The reason why we have not yet implemented Kafka support is that we are no active users of it, and we have no experience or demand right now. But: Of course we would love to support Kafka, and there is no technical reason why this should not or could not be done.

On our roadmap we have at least the task of evaluating Kafka, but we have no timeframe here. It doesn't have a very high priority for us, due to the fact that we are no active users of Kafka, but YMMV.

If you want to help speed things up, we would be happy about a pull request. If you need any help with this, or have questions about the structure of the existing code, especially the tests, we can assist you. Another option would be to have some kind of sponsored development. If you are interested in this, please feel free to get in touch via [mail](mailto:hello@thenativeweb.io).

Does one of these options sound reasonable to you?

**Comment by Protoss78** [comment] 2018-10-04 09:05
Hi,

I've recently thought about that as well. Since I'm heavily involved with Kafka projects for almost 2 years now, I've looked into the inmemory implementation of the event store to see how complex a Kafka implementation would be. 
Unfortunately I've found a few methods that completely contradict the way Kafka works and would be impossible be implemented in the same way:
```Javascript  
  updateEventInDatabaseAtIndex (index, newEventData) {
    this.database.events[index] = newEventData;
  }
```
A Kafka topic is basically an append only log file. It is impossible to update or delete a published event, you can only add a new one. But on the other hand this is exactly the described behavior of an event store. 
What I do not understand is why does Wolkenkit need this functionality at all? I have seen that it is used to mark events as published, but I have not figured out yet why this is necessary?. Is there a documentation about the whole event store interface and its expected behavior?

**Comment by Protoss78** [comment] 2018-10-04 22:16
Hi @goloroden ,

Thanks for the explanation. In the meantime I also had time to look into wolkenkit-core and I think I understand the use case much better now.

The Kafka counterpart for this logic would be the consumer offset. Usually when you consume the latest message from a Kafka topic, it automatically marks the message as successfully delivered. This is done by remembering the unique offset of the consumed message - I think the wolkenkit counterpart in the event metadata would be the position.  
The good news is that this default behavior can be overridden and controlled manually. Following changes would be necessary though:

- Adding offset and partition number to the event metadata
- Change the markEventsAsPublished signature and pass the whole event object in an array, so that we can tell Kafka which offsets have been published.

If I find time this weekend, I might have a quick look into that. Always wanted to test the Javascript Kafka Client anyway. Might be a good use case for that. 😄

**Comment by goloroden** [comment] 2018-10-05 04:10
Wow, that sounds great, thanks a lot! 😊 

There is just one more thing you should know, *before* you may start working on the pull request: We are currently thinking about how to get rid off the `position` field, as this is a major limitation right now (first of all, its range is limited, and second, we need a central sequencer which may be a bottleneck or even worse, a single point of failure).

So our current idea is to store for each event not only its ID, but only the ID of its predecessor, similar to what Git does. We would then use CTEs in the database drivers to fetch the appropriate range of events.

It may make sense to take this into account.

By the way: I would like to invite you to the [wolkenkit Slack](http://slackin.wolkenkit.io/), as for fast discussion this might be the better platform. If you feel more comfortable with staying on GitHub for this, this is fine of course, too.

**Comment by cdimitroulas** [comment] 2018-10-19 11:58
Don't mean to jump in and hijack the conversation here - but @goloroden you asked about other solutions for how to deal with publishing of events.

Now, I am a total DDD/CQRS noob and am completely unfamiliar with how  so don't mind me too much, but from what I see there are two options which don't require updating events in the event store:

1. You write a new event in the event store to say that the previous event was published
2. The process which consumes the events (in this case publishing them to a queue it seems) persists the last event it published so that if it crashes/fails - it will resume from after the last event it published once it restarts (guaranteeing that all events in the event store will eventually be published)

**Comment by goloroden** [comment] 2018-10-21 09:06
@cdimitroulas Thanks a lot for jumping in 😊 

I have tried to think about your suggestion in the past days, and I am not that sure whether this would actually work. The reasons for this are the following:

Ad 1: From time to time multiple events need to be stored at the same time, and so all of them also need to be published. While we can store them in an atomic way (simply run multiple `INSERT` statements in one transaction), we can't publish them in an atomic way. So given the fact that there are succeessor events to a given one does not automatically mean that it was already published (unfortunately).

Ad 2: The problem here is that this consuming process must be able to run in the cloud, and hence it does not have a thing such as a reliable local storage. This means that we would need some external storage, which then needs to be updated, which in turn basically is the same solution that we already have, except that the place of storage would be at a different place.

But maybe I am missing something here, and maybe there's a way to still resolve it. If you want to, would you like to join our [Slack team](http://slackin.wolkenkit.io/) to discuss these things with us?

**Comment by rkaw92** [comment] 2019-02-11 22:40
Hi,
I regret having to derail this, but have you seen https://medium.com/serialized-io/apache-kafka-is-not-for-event-sourcing-81735c3cf5c ?
In short, Kafka is not suitable as an Event Store on its own because it cannot do optimistic concurrency control.

**Comment by goloroden** [comment] 2019-02-12 07:22
@rkaw92 Thanks for the hint and the interesting discussion in Slack yesterday. The results of this have been documented as an issue [here](https://github.com/thenativeweb/wolkenkit/issues/131). Taking all of this together, it actually seems that Kafka has some drawbacks, when used as an event-store.

Hence I am going to close this now, as it is not very probable that we will implement Kafka support given these circumstances (and, this finally provides me with a good answer that I can give to people asking about Kafka as an event-store).

**Closed by goloroden** 2019-02-12 07:22 UTC
